#!/bin/bash
# Vercel Deployment Guide - Terminal Method

echo "=========================================="
echo "NFC Attendance System - Vercel Deployment"
echo "=========================================="
echo ""
echo "Your code is already on GitHub at:"
echo "  https://github.com/Yohannes18/attendance-system"
echo ""
echo "✅ Project setup completed:"
echo "  • Git repository initialized"
echo "  • All files committed"
echo "  • Pushed to GitHub (main branch)"
echo "  • vercel.json configured"
echo ""
echo "=========================================="
echo "NEXT STEP: Deploy on Vercel"
echo "=========================================="
echo ""
echo "Since CLI deployment has connection issues, please use the web interface:"
echo ""
echo "1. Go to: https://vercel.com"
echo "2. Click 'Sign up' → Choose 'Continue with GitHub'"
echo "3. Authorize Vercel to access your GitHub repos"
echo "4. After sign-in, click 'Add New' → 'Project'"
echo "5. Find 'attendance-system' in the list"
echo "6. Click 'Import'"
echo ""
echo "Configuration:"
echo "─────────────"
echo "  Framework: Next.js (auto-detected ✓)"
echo "  Root Directory: ./web (auto-detected ✓)"
echo ""
echo "7. Add Environment Variables:"
echo "   Name: NEXT_PUBLIC_SUPABASE_URL"
echo "   Value: https://lbqlntagejtdifyxvukk.supabase.co"
echo ""
echo "   Name: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Value: sb_publishable_qbzAv4K01SPRxgXs2HaWQg_44_Qjx3Q"
echo ""
echo "8. Click 'Deploy'"
echo ""
echo "After Deployment:"
echo "────────────────"
echo "  • You'll get a live URL (e.g., attendance-system-xyz.vercel.app)"
echo "  • Every git push to 'main' auto-deploys"
echo "  • View deployment logs in dashboard"
echo ""
echo "=========================================="
echo ""
